- name: Install iessvc package
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - iessvc

- name: Copy config-ies template 
  template:
    src: config-ies.txt.j2
    dest: /opt/incognito/ies/data/config.txt

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/share/java/mysql-connector-java.jar
    dest: /opt/incognito/ies/ext/mysql-connector-java.jar
    owner: root
    group: root
    state: link

- name: Make sure iessvc service is running
  systemd:
    name: iessvc
    state: restarted
    daemon_reload: yes
    enabled: yes  