master: false
nodes: false
node1: rabbitmq-1
password: changeme

rabbitmq_repo_yum:
  - name: rabbitmq_server
    description: PackageCloud's repository key and RabbitMQ 
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/8/$basearch
    enabled: 1
    gpgcheck: 0
    state: present

erlang_repo_yum:
  - name: rabbitmq_erlang
    description: PackageCloud's repository key and RabbitMQ package
    baseurl: https://packagecloud.io/rabbitmq/erlang/el/8/$basearch
    enabled: 1
    gpgcheck: 0
    state: present